const padding = {
  p0: { padding: 0 },
  p1: { padding: 5 },
  p2: { padding: 10 },
  p3: { padding: 15 },
  p4: { padding: 20 },
  p5: { padding: 25 },
  pt1: { paddingTop: 5 },
  pt2: { paddingTop: 10 },
  pt3: { paddingTop: 15 },
  pt4: { paddingTop: 20 },
  pt5: { paddingTop: 25 },
  pb1: { paddingBottom: 5 },
  pb2: { paddingBottom: 10 },
  pb3: { paddingBottom: 15 },
  pb4: { paddingBottom: 20 },
  pb5: { paddingBottom: 25 },
  pl1: { paddingLeft: 5 },
  pl2: { paddingLeft: 10 },
  pl3: { paddingLeft: 15 },
  pl4: { paddingLeft: 20 },
  pl5: { paddingLeft: 25 },
  pr1: { paddingRight: 5 },
  pr2: { paddingRight: 10 },
  pr3: { paddingRight: 15 },
  pr4: { paddingRight: 20 },
  pr5: { paddingRight: 25 },
  px0: { paddingLeft: 0, paddingRight:0 },
  px1: { paddingLeft: 5, paddingRight:5 },
  px2: { paddingLeft: 10, paddingRight:10 },
  px3: { paddingLeft: 15, paddingRight:15 },
  px4: { paddingLeft: 20, paddingRight:20 },
  px5: { paddingLeft: 25, paddingRight:25 },
  py0: { paddingTop: 0, paddingBottom:0 },
  py1: { paddingTop: 5, paddingBottom:5 },
  py2: { paddingTop: 10, paddingBottom:10 },
  py3: { paddingTop: 15, paddingBottom:15 },
  py4: { paddingTop: 20, paddingBottom:20 },
  py5: { paddingTop: 25, paddingBottom:25 },
  
  
};

export default padding;